source 'https://github.com/CocoaPods/Specs.git'

project './KTMosaicLayout/KTMosaicLayout.xcodeproj'
use_frameworks!
inhibit_all_warnings!

def shared_pods

  # Utilities
  pod 'SwiftGen',  '~> 5.3.0'
  pod 'SwiftLint', '~> 0.25.0'

  # UI
  pod 'Reusable', '~> 4.0.0'

end

target 'KTMosaicLayout iOS' do
  platform :ios, '9.0'

  shared_pods

  # Development
  pod 'KTMosaicLayout', :path => '../'

end

target 'KTMosaicLayout tvOS' do
  platform :tvos, '9.0'

  shared_pods

  # Development
  pod 'KTMosaicLayout', :path => '../'

end
